// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.17.3
// source: task.proto

package task

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNKNOWN     TaskStatus = 0
	TaskStatus_TASK_STATUS_BACKLOG     TaskStatus = 1
	TaskStatus_TASK_STATUS_TODO        TaskStatus = 2
	TaskStatus_TASK_STATUS_IN_PROGRESS TaskStatus = 3
	TaskStatus_TASK_STATUS_IN_REVIEW   TaskStatus = 4
	TaskStatus_TASK_STATUS_DONE        TaskStatus = 5
	TaskStatus_TASK_STATUS_CANCELED    TaskStatus = 6
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNKNOWN",
		1: "TASK_STATUS_BACKLOG",
		2: "TASK_STATUS_TODO",
		3: "TASK_STATUS_IN_PROGRESS",
		4: "TASK_STATUS_IN_REVIEW",
		5: "TASK_STATUS_DONE",
		6: "TASK_STATUS_CANCELED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNKNOWN":     0,
		"TASK_STATUS_BACKLOG":     1,
		"TASK_STATUS_TODO":        2,
		"TASK_STATUS_IN_PROGRESS": 3,
		"TASK_STATUS_IN_REVIEW":   4,
		"TASK_STATUS_DONE":        5,
		"TASK_STATUS_CANCELED":    6,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskResponse) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status        *TaskStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=task.TaskStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTaskRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *UpdateTaskRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateTaskRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateTaskRequest) GetStatus() TaskStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return TaskStatus_TASK_STATUS_UNKNOWN
}

type GetTaskByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskByIDRequest) Reset() {
	*x = GetTaskByIDRequest{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskByIDRequest) ProtoMessage() {}

func (x *GetTaskByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTaskByIDRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskByIDRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        TaskStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=task.TaskStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

func (x *Task) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNKNOWN
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetTaskByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskByIDResponse) Reset() {
	*x = GetTaskByIDResponse{}
	mi := &file_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskByIDResponse) ProtoMessage() {}

func (x *GetTaskByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskByIDResponse.ProtoReflect.Descriptor instead.
func (*GetTaskByIDResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskByIDResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTaskRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchTitle   *string                `protobuf:"bytes,1,opt,name=search_title,json=searchTitle,proto3,oneof" json:"search_title,omitempty"`
	SearchStatus  *TaskStatus            `protobuf:"varint,2,opt,name=search_status,json=searchStatus,proto3,enum=task.TaskStatus,oneof" json:"search_status,omitempty"`
	CreatedFrom   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_from,json=createdFrom,proto3,oneof" json:"created_from,omitempty"`
	CreatedTo     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_to,json=createdTo,proto3,oneof" json:"created_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{7}
}

func (x *Filter) GetSearchTitle() string {
	if x != nil && x.SearchTitle != nil {
		return *x.SearchTitle
	}
	return ""
}

func (x *Filter) GetSearchStatus() TaskStatus {
	if x != nil && x.SearchStatus != nil {
		return *x.SearchStatus
	}
	return TaskStatus_TASK_STATUS_UNKNOWN
}

func (x *Filter) GetCreatedFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedFrom
	}
	return nil
}

func (x *Filter) GetCreatedTo() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTo
	}
	return nil
}

type Sort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *string                `protobuf:"bytes,1,opt,name=field,proto3,oneof" json:"field,omitempty"`
	Order         *string                `protobuf:"bytes,2,opt,name=order,proto3,oneof" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sort) Reset() {
	*x = Sort{}
	mi := &file_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{8}
}

func (x *Sort) GetField() string {
	if x != nil && x.Field != nil {
		return *x.Field
	}
	return ""
}

func (x *Sort) GetOrder() string {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return ""
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint64                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{9}
}

func (x *Pagination) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetTasksByFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	Sort          *Sort                  `protobuf:"bytes,2,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksByFilterRequest) Reset() {
	*x = GetTasksByFilterRequest{}
	mi := &file_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksByFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksByFilterRequest) ProtoMessage() {}

func (x *GetTasksByFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksByFilterRequest.ProtoReflect.Descriptor instead.
func (*GetTasksByFilterRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{10}
}

func (x *GetTasksByFilterRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetTasksByFilterRequest) GetSort() *Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *GetTasksByFilterRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetTasksByFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksByFilterResponse) Reset() {
	*x = GetTasksByFilterResponse{}
	mi := &file_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksByFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksByFilterResponse) ProtoMessage() {}

func (x *GetTasksByFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksByFilterResponse.ProtoReflect.Descriptor instead.
func (*GetTasksByFilterResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{11}
}

func (x *GetTasksByFilterResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\x04task\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"_\n" +
	"\x11CreateTaskRequest\x12\x1f\n" +
	"\x05title\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x05\x18 R\x05title\x12)\n" +
	"\vdescription\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vdescription\"-\n" +
	"\x12CreateTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\"\xd6\x01\n" +
	"\x11UpdateTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x12$\n" +
	"\x05title\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x05\x18 H\x00R\x05title\x88\x01\x01\x12.\n" +
	"\vdescription\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01H\x01R\vdescription\x88\x01\x01\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x10.task.TaskStatusH\x02R\x06status\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_status\"-\n" +
	"\x12GetTaskByIDRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\"\xb3\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12(\n" +
	"\x06status\x18\x04 \x01(\x0e2\x10.task.TaskStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"5\n" +
	"\x13GetTaskByIDResponse\x12\x1e\n" +
	"\x04task\x18\x01 \x01(\v2\n" +
	".task.TaskR\x04task\",\n" +
	"\x11DeleteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\"\xb3\x02\n" +
	"\x06Filter\x12&\n" +
	"\fsearch_title\x18\x01 \x01(\tH\x00R\vsearchTitle\x88\x01\x01\x12:\n" +
	"\rsearch_status\x18\x02 \x01(\x0e2\x10.task.TaskStatusH\x01R\fsearchStatus\x88\x01\x01\x12B\n" +
	"\fcreated_from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\vcreatedFrom\x88\x01\x01\x12>\n" +
	"\n" +
	"created_to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\tcreatedTo\x88\x01\x01B\x0f\n" +
	"\r_search_titleB\x10\n" +
	"\x0e_search_statusB\x0f\n" +
	"\r_created_fromB\r\n" +
	"\v_created_to\"\x84\x01\n" +
	"\x04Sort\x12;\n" +
	"\x05field\x18\x01 \x01(\tB \xbaH\x1dr\x1bR\x05titleR\x06statusR\n" +
	"created_atH\x00R\x05field\x88\x01\x01\x12+\n" +
	"\x05order\x18\x02 \x01(\tB\x10\xbaH\rr\vR\x03ascR\x04descH\x01R\x05order\x88\x01\x01B\b\n" +
	"\x06_fieldB\b\n" +
	"\x06_order\":\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\"\xc3\x01\n" +
	"\x17GetTasksByFilterRequest\x12)\n" +
	"\x06filter\x18\x01 \x01(\v2\f.task.FilterH\x00R\x06filter\x88\x01\x01\x12#\n" +
	"\x04sort\x18\x02 \x01(\v2\n" +
	".task.SortH\x01R\x04sort\x88\x01\x01\x125\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x10.task.PaginationH\x02R\n" +
	"pagination\x88\x01\x01B\t\n" +
	"\a_filterB\a\n" +
	"\x05_sortB\r\n" +
	"\v_pagination\"<\n" +
	"\x18GetTasksByFilterResponse\x12 \n" +
	"\x05tasks\x18\x01 \x03(\v2\n" +
	".task.TaskR\x05tasks*\xbc\x01\n" +
	"\n" +
	"TaskStatus\x12\x17\n" +
	"\x13TASK_STATUS_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_BACKLOG\x10\x01\x12\x14\n" +
	"\x10TASK_STATUS_TODO\x10\x02\x12\x1b\n" +
	"\x17TASK_STATUS_IN_PROGRESS\x10\x03\x12\x19\n" +
	"\x15TASK_STATUS_IN_REVIEW\x10\x04\x12\x14\n" +
	"\x10TASK_STATUS_DONE\x10\x05\x12\x18\n" +
	"\x14TASK_STATUS_CANCELED\x10\x062\xe3\x02\n" +
	"\vTaskService\x12?\n" +
	"\n" +
	"CreateTask\x12\x17.task.CreateTaskRequest\x1a\x18.task.CreateTaskResponse\x12=\n" +
	"\n" +
	"UpdateTask\x12\x17.task.UpdateTaskRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\vGetTaskByID\x12\x18.task.GetTaskByIDRequest\x1a\x19.task.GetTaskByIDResponse\x12=\n" +
	"\n" +
	"DeleteTask\x12\x17.task.DeleteTaskRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x10GetTasksByFilter\x12\x1d.task.GetTasksByFilterRequest\x1a\x1e.task.GetTasksByFilterResponseB2Z0github.com/rovioletta/todo-list/pkg/pb/task;taskb\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_task_proto_goTypes = []any{
	(TaskStatus)(0),                  // 0: task.TaskStatus
	(*CreateTaskRequest)(nil),        // 1: task.CreateTaskRequest
	(*CreateTaskResponse)(nil),       // 2: task.CreateTaskResponse
	(*UpdateTaskRequest)(nil),        // 3: task.UpdateTaskRequest
	(*GetTaskByIDRequest)(nil),       // 4: task.GetTaskByIDRequest
	(*Task)(nil),                     // 5: task.Task
	(*GetTaskByIDResponse)(nil),      // 6: task.GetTaskByIDResponse
	(*DeleteTaskRequest)(nil),        // 7: task.DeleteTaskRequest
	(*Filter)(nil),                   // 8: task.Filter
	(*Sort)(nil),                     // 9: task.Sort
	(*Pagination)(nil),               // 10: task.Pagination
	(*GetTasksByFilterRequest)(nil),  // 11: task.GetTasksByFilterRequest
	(*GetTasksByFilterResponse)(nil), // 12: task.GetTasksByFilterResponse
	(*timestamppb.Timestamp)(nil),    // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 14: google.protobuf.Empty
}
var file_task_proto_depIdxs = []int32{
	0,  // 0: task.UpdateTaskRequest.status:type_name -> task.TaskStatus
	0,  // 1: task.Task.status:type_name -> task.TaskStatus
	13, // 2: task.Task.created_at:type_name -> google.protobuf.Timestamp
	5,  // 3: task.GetTaskByIDResponse.task:type_name -> task.Task
	0,  // 4: task.Filter.search_status:type_name -> task.TaskStatus
	13, // 5: task.Filter.created_from:type_name -> google.protobuf.Timestamp
	13, // 6: task.Filter.created_to:type_name -> google.protobuf.Timestamp
	8,  // 7: task.GetTasksByFilterRequest.filter:type_name -> task.Filter
	9,  // 8: task.GetTasksByFilterRequest.sort:type_name -> task.Sort
	10, // 9: task.GetTasksByFilterRequest.pagination:type_name -> task.Pagination
	5,  // 10: task.GetTasksByFilterResponse.tasks:type_name -> task.Task
	1,  // 11: task.TaskService.CreateTask:input_type -> task.CreateTaskRequest
	3,  // 12: task.TaskService.UpdateTask:input_type -> task.UpdateTaskRequest
	4,  // 13: task.TaskService.GetTaskByID:input_type -> task.GetTaskByIDRequest
	7,  // 14: task.TaskService.DeleteTask:input_type -> task.DeleteTaskRequest
	11, // 15: task.TaskService.GetTasksByFilter:input_type -> task.GetTasksByFilterRequest
	2,  // 16: task.TaskService.CreateTask:output_type -> task.CreateTaskResponse
	14, // 17: task.TaskService.UpdateTask:output_type -> google.protobuf.Empty
	6,  // 18: task.TaskService.GetTaskByID:output_type -> task.GetTaskByIDResponse
	14, // 19: task.TaskService.DeleteTask:output_type -> google.protobuf.Empty
	12, // 20: task.TaskService.GetTasksByFilter:output_type -> task.GetTasksByFilterResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	file_task_proto_msgTypes[2].OneofWrappers = []any{}
	file_task_proto_msgTypes[7].OneofWrappers = []any{}
	file_task_proto_msgTypes[8].OneofWrappers = []any{}
	file_task_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		EnumInfos:         file_task_proto_enumTypes,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
