syntax = "proto3";

package user;

option go_package = "github.com/rovioletta/todo-list/pkg/pb/user;user";

import "buf/validate/validate.proto";

service UserService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
}

message RegisterRequest {
  string login = 1 [(buf.validate.field).string = {
    pattern: "^[a-zA-Z0-9_-]+$"
    min_len: 5,
    max_len: 32
  }];
  string password = 2 [(buf.validate.field).string = {
    min_len: 8,
    max_len: 72
  }];
}

message RegisterResponse {
  uint64 user_id = 1;
}

message LoginRequest {
  string login = 1[(buf.validate.field).string = {
    pattern: "^[a-zA-Z0-9_-]+$"
    min_len: 5,
    max_len: 32
  }];
  string password = 2 [(buf.validate.field).string = {
    min_len: 8,
    max_len: 72
  }];
}

message LoginResponse {
  string token = 1;
}