// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create-task.sql

package db

import (
	"context"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, description, status)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateTaskParams struct {
	Title       string
	Description string
	Status      TaskStatus
}

func (q *Queries) CreateTask(ctx context.Context, arg *CreateTaskParams) (uint64, error) {
	row := q.db.QueryRow(ctx, createTask, arg.Title, arg.Description, arg.Status)
	var id uint64
	err := row.Scan(&id)
	return id, err
}
