// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create-user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (login, password_hash)
VALUES ($1, $2)
RETURNING id
`

func (q *Queries) CreateUser(ctx context.Context, login string, passwordHash string) (uint64, error) {
	row := q.db.QueryRow(ctx, createUser, login, passwordHash)
	var id uint64
	err := row.Scan(&id)
	return id, err
}
