// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create-user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (login, password_hash)
VALUES ($1, $2)
`

func (q *Queries) CreateUser(ctx context.Context, login string, passwordHash string) error {
	_, err := q.db.Exec(ctx, createUser, login, passwordHash)
	return err
}
