// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete-task.sql

package db

import (
	"context"
)

const deleteTask = `-- name: DeleteTask :one
DELETE FROM tasks WHERE id = $1::integer
RETURNING id
`

func (q *Queries) DeleteTask(ctx context.Context, id uint64) (uint64, error) {
	row := q.db.QueryRow(ctx, deleteTask, id)
	var id_2 uint64
	err := row.Scan(&id_2)
	return id_2, err
}
