// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get-tasks-by-filter.sql

package db

import (
	"context"
	"time"
)

const getTasksByFilter = `-- name: GetTasksByFilter :many
SELECT
  id, title, description, status, created_at
FROM
  tasks
WHERE
  -- by title
  ($1::text IS NULL OR title LIKE CONCAT('%', $1::text, '%'))

  -- by status
  AND ($2::text IS NULL OR LOWER(status::text) = LOWER($2::text))

  -- by created_at
  AND ($3::timestamp IS NULL OR created_at >= $3)
  AND ($4::timestamp IS NULL OR created_at <= $4)
  
ORDER BY
  -- by title
  CASE WHEN $5::text = 'title' AND $6::text = 'asc' THEN title END ASC,
  CASE WHEN $5::text = 'title' AND $6::text = 'desc' THEN title END DESC,

  -- by status
  CASE WHEN $5::text = 'status' AND $6::text = 'asc' THEN status END ASC,
  CASE WHEN $5::text = 'status' AND $6::text = 'desc' THEN status END DESC,
  
  -- by created_at
  CASE WHEN $5::text = 'created_at' AND $6::text = 'asc' THEN created_at END ASC,
  CASE WHEN $5::text = 'created_at' AND $6::text = 'desc' THEN created_at END DESC,
  
  -- default
  created_at DESC
LIMIT
  $8::integer OFFSET $7::integer
`

type GetTasksByFilterParams struct {
	FilterSearchTitle  *string
	FilterSearchStatus *string
	FilterCreatedFrom  *time.Time
	FilterCreatedTo    *time.Time
	OrderByField       *string
	OrderType          *string
	Offset             uint64
	Limit              uint64
}

func (q *Queries) GetTasksByFilter(ctx context.Context, arg *GetTasksByFilterParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksByFilter,
		arg.FilterSearchTitle,
		arg.FilterSearchStatus,
		arg.FilterCreatedFrom,
		arg.FilterCreatedTo,
		arg.OrderByField,
		arg.OrderType,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
