// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get-task-by-id.sql

package db

import (
	"context"
)

const getTaskByID = `-- name: GetTaskByID :one
SELECT
  id, title, description, status, created_at
FROM
  tasks
WHERE
  id = $1 :: integer
LIMIT
  1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uint64) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
