// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get-user-by-login.sql

package db

import (
	"context"
)

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT login, password_hash FROM users
WHERE login = $1 :: text
LIMIT 1
`

type GetUserByLoginRow struct {
	Login        string
	PasswordHash string
}

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (GetUserByLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i GetUserByLoginRow
	err := row.Scan(&i.Login, &i.PasswordHash)
	return i, err
}
