// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update-task.sql

package db

import (
	"context"
)

const updateTask = `-- name: UpdateTask :one
UPDATE
  tasks
SET
  title = COALESCE($1, title),
  description = COALESCE($2, description),
  status = COALESCE($3 :: task_status, status)
WHERE
  id = $4 :: integer
RETURNING id
`

type UpdateTaskParams struct {
	NewTitle       *string
	NewDescription *string
	Status         *TaskStatus
	ID             uint64
}

func (q *Queries) UpdateTask(ctx context.Context, arg *UpdateTaskParams) (uint64, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.NewTitle,
		arg.NewDescription,
		arg.Status,
		arg.ID,
	)
	var id uint64
	err := row.Scan(&id)
	return id, err
}
